-- CreateTable
CREATE TABLE `next_user` (
    `user_id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_email` VARCHAR(191) NOT NULL,
    `user_name` VARCHAR(191) NULL,
    `user_password` VARCHAR(191) NOT NULL,
    `user_avatar` VARCHAR(191) NULL,
    `user_phone` VARCHAR(191) NULL,
    `role_id` INTEGER NOT NULL,
    `user_status` ENUM('ACTIVE', 'INACTIVE', 'LOCKED') NOT NULL DEFAULT 'ACTIVE',
    `last_login_time` DATETIME(3) NULL,
    `last_login_ip` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `next_user_user_email_key`(`user_email`),
    UNIQUE INDEX `next_user_user_phone_key`(`user_phone`),
    INDEX `next_user_user_email_idx`(`user_email`),
    INDEX `next_user_user_phone_idx`(`user_phone`),
    INDEX `next_user_role_id_idx`(`role_id`),
    PRIMARY KEY (`user_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `next_role` (
    `role_id` INTEGER NOT NULL AUTO_INCREMENT,
    `role_name` VARCHAR(191) NOT NULL,
    `role_code` VARCHAR(191) NOT NULL,
    `permissions` JSON NOT NULL,
    `role_remark` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `next_role_role_name_key`(`role_name`),
    UNIQUE INDEX `next_role_role_code_key`(`role_code`),
    INDEX `next_role_role_code_idx`(`role_code`),
    PRIMARY KEY (`role_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `next_video` (
    `video_id` INTEGER NOT NULL AUTO_INCREMENT,
    `type_id` INTEGER NOT NULL DEFAULT 0,
    `type_id_1` INTEGER NOT NULL DEFAULT 0,
    `group_id` INTEGER NOT NULL DEFAULT 0,
    `video_name` VARCHAR(191) NOT NULL DEFAULT '',
    `video_sub` VARCHAR(191) NOT NULL DEFAULT '',
    `video_en` VARCHAR(191) NOT NULL DEFAULT '',
    `video_status` INTEGER NOT NULL DEFAULT 0,
    `video_letter` CHAR(1) NOT NULL DEFAULT '',
    `video_color` VARCHAR(6) NOT NULL DEFAULT '',
    `video_tag` VARCHAR(191) NOT NULL DEFAULT '',
    `video_class` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pic` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pic_thumb` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pic_slide` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pic_screenshot` TEXT NULL,
    `video_actor` VARCHAR(191) NOT NULL DEFAULT '',
    `video_director` VARCHAR(191) NOT NULL DEFAULT '',
    `video_writer` VARCHAR(191) NOT NULL DEFAULT '',
    `video_behind` VARCHAR(191) NOT NULL DEFAULT '',
    `video_blurb` VARCHAR(191) NOT NULL DEFAULT '',
    `video_remarks` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pubdate` VARCHAR(191) NOT NULL DEFAULT '',
    `video_total` INTEGER NOT NULL DEFAULT 0,
    `video_serial` VARCHAR(191) NOT NULL DEFAULT '0',
    `video_tv` VARCHAR(191) NOT NULL DEFAULT '',
    `video_weekday` VARCHAR(191) NOT NULL DEFAULT '',
    `video_area` VARCHAR(191) NOT NULL DEFAULT '',
    `video_lang` VARCHAR(191) NOT NULL DEFAULT '',
    `video_year` VARCHAR(191) NOT NULL DEFAULT '',
    `video_version` VARCHAR(191) NOT NULL DEFAULT '',
    `video_state` VARCHAR(191) NOT NULL DEFAULT '',
    `video_author` VARCHAR(191) NOT NULL DEFAULT '',
    `video_jumpurl` VARCHAR(191) NOT NULL DEFAULT '',
    `video_tpl` VARCHAR(191) NOT NULL DEFAULT '',
    `video_tpl_play` VARCHAR(191) NOT NULL DEFAULT '',
    `video_tpl_down` VARCHAR(191) NOT NULL DEFAULT '',
    `video_isend` INTEGER NOT NULL DEFAULT 0,
    `video_lock` INTEGER NOT NULL DEFAULT 0,
    `video_level` INTEGER NOT NULL DEFAULT 0,
    `video_copyright` INTEGER NOT NULL DEFAULT 0,
    `video_points` INTEGER NOT NULL DEFAULT 0,
    `video_points_play` INTEGER NOT NULL DEFAULT 0,
    `video_points_down` INTEGER NOT NULL DEFAULT 0,
    `video_hits` INTEGER NOT NULL DEFAULT 0,
    `video_hits_day` INTEGER NOT NULL DEFAULT 0,
    `video_hits_week` INTEGER NOT NULL DEFAULT 0,
    `video_hits_month` INTEGER NOT NULL DEFAULT 0,
    `video_duration` VARCHAR(191) NOT NULL DEFAULT '',
    `video_up` INTEGER NOT NULL DEFAULT 0,
    `video_down` INTEGER NOT NULL DEFAULT 0,
    `video_score` DECIMAL(3, 1) NOT NULL DEFAULT 0,
    `video_score_all` INTEGER NOT NULL DEFAULT 0,
    `video_score_num` INTEGER NOT NULL DEFAULT 0,
    `video_time` INTEGER NOT NULL DEFAULT 0,
    `video_time_add` INTEGER NOT NULL DEFAULT 0,
    `video_time_hits` INTEGER NOT NULL DEFAULT 0,
    `video_time_make` INTEGER NOT NULL DEFAULT 0,
    `video_trysee` INTEGER NOT NULL DEFAULT 0,
    `video_douban_id` INTEGER NOT NULL DEFAULT 0,
    `video_douban_score` DECIMAL(3, 1) NOT NULL DEFAULT 0,
    `video_reurl` VARCHAR(191) NOT NULL DEFAULT '',
    `video_rel_vod` VARCHAR(191) NOT NULL DEFAULT '',
    `video_rel_art` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pwd` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pwd_url` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pwd_play` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pwd_play_url` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pwd_down` VARCHAR(191) NOT NULL DEFAULT '',
    `video_pwd_down_url` VARCHAR(191) NOT NULL DEFAULT '',
    `video_content` TEXT NOT NULL,
    `video_play_from` VARCHAR(191) NOT NULL DEFAULT '',
    `video_play_server` VARCHAR(191) NOT NULL DEFAULT '',
    `video_play_note` VARCHAR(191) NOT NULL DEFAULT '',
    `video_play_url` MEDIUMTEXT NOT NULL,
    `video_down_from` VARCHAR(191) NOT NULL DEFAULT '',
    `video_down_server` VARCHAR(191) NOT NULL DEFAULT '',
    `video_down_note` VARCHAR(191) NOT NULL DEFAULT '',
    `video_down_url` MEDIUMTEXT NOT NULL,
    `video_plot` INTEGER NOT NULL DEFAULT 0,
    `video_plot_name` MEDIUMTEXT NOT NULL,
    `video_plot_detail` MEDIUMTEXT NOT NULL,

    INDEX `next_video_type_id_idx`(`type_id`),
    INDEX `next_video_type_id_1_idx`(`type_id_1`),
    INDEX `next_video_video_level_idx`(`video_level`),
    INDEX `next_video_video_hits_idx`(`video_hits`),
    INDEX `next_video_video_letter_idx`(`video_letter`),
    INDEX `next_video_video_name_idx`(`video_name`),
    INDEX `next_video_video_year_idx`(`video_year`),
    INDEX `next_video_video_area_idx`(`video_area`),
    INDEX `next_video_video_lang_idx`(`video_lang`),
    INDEX `next_video_video_tag_idx`(`video_tag`),
    INDEX `next_video_video_class_idx`(`video_class`),
    INDEX `next_video_video_lock_idx`(`video_lock`),
    INDEX `next_video_video_up_idx`(`video_up`),
    INDEX `next_video_video_down_idx`(`video_down`),
    INDEX `next_video_video_en_idx`(`video_en`),
    INDEX `next_video_video_hits_day_idx`(`video_hits_day`),
    INDEX `next_video_video_hits_week_idx`(`video_hits_week`),
    INDEX `next_video_video_hits_month_idx`(`video_hits_month`),
    INDEX `next_video_video_plot_idx`(`video_plot`),
    INDEX `next_video_video_points_play_idx`(`video_points_play`),
    INDEX `next_video_video_points_down_idx`(`video_points_down`),
    INDEX `next_video_group_id_idx`(`group_id`),
    INDEX `next_video_video_time_add_idx`(`video_time_add`),
    INDEX `next_video_video_time_idx`(`video_time`),
    INDEX `next_video_video_time_make_idx`(`video_time_make`),
    INDEX `next_video_video_actor_idx`(`video_actor`),
    INDEX `next_video_video_director_idx`(`video_director`),
    INDEX `next_video_video_score_all_idx`(`video_score_all`),
    INDEX `next_video_video_score_num_idx`(`video_score_num`),
    INDEX `next_video_video_total_idx`(`video_total`),
    INDEX `next_video_video_score_idx`(`video_score`),
    INDEX `next_video_video_version_idx`(`video_version`),
    INDEX `next_video_video_state_idx`(`video_state`),
    INDEX `next_video_video_isend_idx`(`video_isend`),
    PRIMARY KEY (`video_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `next_user` ADD CONSTRAINT `next_user_role_id_fkey` FOREIGN KEY (`role_id`) REFERENCES `next_role`(`role_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
